### ISSUE TITLE
TODO Items

### ISSUE THREAD

**Issue by Innixma** [adibiasio/early-stopping#1]
1. Rename `requirements.txt` to `requirements_frozen.txt`
2. Make a `requirements.txt` that doesn't use hard-coded exact versions for ease of install.
3. Mention in README.md what Python versions have been tested.
4. Move code into `early_stopping` directory. Keep tests in root.
5. Add `__init__.py` files: https://github.com/autogluon/tabrepo/tree/main/tabrepo
6. Use relative imports: https://github.com/autogluon/tabrepo/blob/main/tabrepo/repository/evaluation_repository.py#L8-L15
7. avoid circular imports with typing import
8. Don't capitalize python files
9. Why is `autogluon.common` not a dependency? Why is the `s3_utils.py` file copy pasting `autogluon.common` code?
10. Why does `download_folder` exist when `autogluon.common.utils.s3_utils.download_s3_folder` can be used instead?
11. Optimize efficiency: data format (numpy objects?) or simulation code efficiency
12. remove 'simple' kwarg from autogluon strategy and separate into two different classes)
13. remove setting of b in feature patience strategy (use min_patience/max_patience to replicate simple AG)
14. get rid of base_class / base_name functionality in polynomial patience
15. feature patience max patience is ok, but in actual AG strategy max_p is only used to calculate min_patience (not then passed into Adaptive ES for max_patience bound)

For references on how to structure a project, look at TabRepo: https://github.com/autogluon/tabrepo

**Comment by adibiasio** [comment]
Addressed by #5
